name: Release npm package

on:
  push:
    branches:
      - beta
# on:
#   push:
#     tags:
#       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: yarn
      - name: build
        run: yarn run build:lib
      - name: upload
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ng-multiselect-dropdown
          path: dist-lib
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: ng-multiselect-dropdown
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: publish
        run: yarn publish --access public
        continue-on-error: false
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
